services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "${postgres_port}:5432"
    environment:
      POSTGRESQL_USERNAME: ${postgres_username}
      POSTGRESQL_PASSWORD: ${postgres_password}
    volumes:
      - fintrack_pg_data:/bitnami/postgresql

  spring-api:
    build:
      context: database-docker
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  fintrack_pg_data:
